version: '3.8'

services:
  mysql:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dummy.sql:/docker-entrypoint-initdb.d/dummy.sql
    command:
      --default-authentication-plugin=mysql_native_password  # Menggunakan plugin autentikasi yang kompatibel
    networks:
      - mysql-network

volumes:
  mysql-data:
    name: mysql-data

networks:
  mysql-network:
    driver: bridge